apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-svc-monitor
  namespace: monitoring
  labels:
    testlabel: testvalue
spec:
  endpoints:
  - interval: 15s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
