apiVersion: v1
kind: Namespace
metadata:
  name: testy-dev1

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testy-dev1
  namespace: testy-dev1
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: testy-dev1
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'
