apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager-main
  namespace: testy-dev1
spec:
  rules:
  - host: alertmanager.skrypalle.dk
    http:
      paths:
      - backend:
          serviceName: alertmanager-main
          servicePort: web
        path: /
