apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testy-dev1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: testy-dev1
  source:
    repoURL: https://github.com/pskry/argo-cd
    path: testy-dev1
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: testy-dev1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
