apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-root-app
  namespace: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  source:
    repoURL: https://github.com/pskry/argo-cd
    path: test-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
