argo-cd:
  global:
    installCRDs: false
    image:
      repository: docker.io/alinbalutoiu/argocd
  server:
    extraArgs:
      - "--insecure"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: "letsencrypt-stg"
        cert-manager.io/issuer-kind: ClusterIssuer
      hosts:
        - argocd.skrypalle.dk
      tls:
        - hosts:
            - argocd.skrypalle.dk
          secretName: tls-argocd-server-ingress
    configEnabled: true
    config:
  #    url: https://argocd.skrypalle.dk
      repositories: |
        - type: git
          url: https://github.com/pskry/argo-cd.git
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: redis-ha
          url: https://dandydeveloper.github.io/charts
    additionalApplications:
      - name: argocd-apps
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd-project
        source:
          path: apps
          repoURL: https://github.com/pskry/argo-cd.git
          targetRevision: HEAD
          directory:
            recurse: true
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
      - name: argocd-projects
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd-project
        source:
          path: app-projects
          repoURL: https://github.com/pskry/argo-cd.git
          targetRevision: HEAD
          directory:
            recurse: true
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
