apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sample-project
  source:
    repoURL: https://github.com/wenerme/charts
    path: alpine
    targetRevision: HEAD
    helm:
      releaseName: helm-test
  destination:
    namespace: sample-app
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
